# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'github-search-task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-search-task
  pod 'Moya', '~> 15.0'
  pod 'SnapKit', '~> 5.0.0'

  target 'github-search-taskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'github-search-taskUITests' do
    # Pods for testing
  end

end
